---
- name: Pull Docker image of backend
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      shell: docker pull vamshi07/backend:latest
    - name: Running container
      shell: docker create -it  --name backend vamshi07/backend